### ISSUE TITLE
disable objects

### ISSUE THREAD

**Issue by rdfriedl** [chandlerprall/Physijs#233]
im new to JavaScript physics libraries so if you dont mind i could use some help.
i plan to build a game with ThreeJS.
the ground in the game will consist of around 20 Compound Shapes, each one containing about 1000 collision objects.
i was wandering if its possible to disable the physics of Mesh, but keep the Mesh in the scene so it would still be visible.
and then later on add the Mesh back into the physics, so that the player could collide with it.

the reason i want to do this,is so that i can have complex ground collisions and only processes the one the player is standing on, then when the player moves to enable/disable parts of the ground, but still keep them visible.

**Comment by joantune** [comment]
did you manage to do this @rdfriedl  ?

**Comment by hzrd149** [comment]
Sorry @joantune I dont think I was able to find a solution :disappointed: 
I ended up writing my own AABB collision logic to handle physics in my game.

Although its possible that physijs supports disabling objects now, since its been almost three years since I opened this issue, and a lot can change in three years
